### ISSUE TITLE
the CEDAR dataset link was not opened , please help.

### ISSUE THREAD

**Issue by devendraswamy** [DefUs3r/Automatic-Signature-Verification#1]
Not Found
The requested URL /NIJ/data/signatures was not found on this server.

Apache/2.2.15 (CentOS) Server at www.cedar.Buffalo.Edu Port 443

**Comment by DefUs3r** [comment]
Hi,
Sorry for the delay in responding.
The dataset can be found [at this link](http://www.cedar.buffalo.edu/NIJ/data/signatures.rar).

Regds.
